name: miverva_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  font_awesome_flutter: 7.1.0
  video_player: 0.6.4
  connectivity: 0.3.1
  device_info: 0.2.1
  chewie: 0.6.1
  shared_preferences: 0.4.2
  diacritic: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
      - assets/data/cards.json
      - assets/data/regular_units.json
      - assets/icons/area.png
      - assets/icons/currency.png
      - assets/icons/digital_storage.png
      - assets/icons/length.png
      - assets/icons/mass.png
      - assets/icons/power.png
      - assets/icons/time.png
      - assets/icons/volume.png
      - assets/images/perfil.jpg
      - assets/icons/banana.png
      - assets/icons/seta.png
      - assets/icons/price.png
      - assets/icons/morango.png
      - assets/icons/abacate.png
      - assets/icons/videogame.png
      - assets/icons/livro.png
      - assets/icons/bola.png
      - assets/icons/pizza.png
      - assets/icons/escova.png
      - assets/icons/remédio.png
      - assets/icons/curativo.png
      - assets/icons/dicionário.png


      - assets/gif/desperdicio.gif
      - assets/icons/building.png
      - assets/icons/graph.png
      - assets/icons/growth.png
      - assets/icons/teamwork.png
      - assets/icons/desafios.png
      - assets/icons/trofeu.png
      - assets/icons/medalha.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
     - family: Ubuntu
       fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
